/**
 * Daily Aathichoodi Series — Slide 3 Photo Prompt Builder
 * ----------------------------------------------------------------------------
 * This app never generates or fetches images itself (same "no AI/LLM call
 * anywhere in this app" constraint as content-engine.ts) -- Slide 3's
 * optional family photo is generated by the founder in an external AI
 * image tool and uploaded via the workspace sidebar (see
 * aathichoodi-carousel-design-store.ts's loadFamilyImage/saveFamilyImage).
 *
 * This is a deterministic text transform, not a call to any model: it
 * turns that episode's own family-scenario copy into a ready-to-paste
 * prompt so the photo matches the "IT HAPPENS AT HOME" text instead of
 * being generic. "Warm realistic photography" is the one house style used
 * across the whole series, per explicit founder direction, so photos feel
 * consistent episode to episode rather than each looking like a different
 * generator/style.
 */

/** Best-effort rewrite of the second-person scenario copy ("Your child
 *  sees...") into a third-person scene description an image generator can
 *  act on ("A child sees..."). Plain word-boundary substitutions, not a
 *  grammar engine -- review the result before pasting it into a generator. */
function toSceneDescription(text: string): string {
  return text
    .replace(/\bYour older child\b/g, "An older child")
    .replace(/\bYour younger child\b/g, "A younger child")
    .replace(/\bYour child\b/g, "A child")
    .replace(/\byour child\b/g, "a child")
    .replace(/\byour children\b/gi, "the children")
    .replace(/\byour family\b/gi, "the family")
    .replace(/\byour\b/gi, "their")
    .replace(/\byou\b/gi, "they");
}

/** familyAngleText should be whatever's CURRENTLY shown on Slide 3 (the
 *  generated scenario, or the founder's own text override if one is set)
 *  so the prompt always matches what the slide actually says. */
export function buildFamilyImagePrompt(familyAngleText: string): string {
  const scene = toSceneDescription(familyAngleText.trim());
  return [
    `Warm, realistic documentary-style family photograph. Scene: ${scene}`,
    "Natural window light, candid and unposed, soft warm tones, genuine expressions, real everyday home setting.",
    "Vertical portrait composition (roughly 4:5 aspect ratio), main subject placed slightly off-center with breathing room in the frame.",
    "Photorealistic only -- no text, no logos, no watermarks, no illustration or cartoon style.",
  ].join(" ");
}
