/**
 * Daily Aathichoodi Series — Slide 3 Photo Prompt Builder
 * ----------------------------------------------------------------------------
 * This app never generates or fetches images itself (same "no AI/LLM call
 * anywhere in this app" constraint as content-engine.ts) -- Slide 3's
 * optional family photo is generated by the founder in an external AI
 * image tool and uploaded via the workspace sidebar (see
 * aathichoodi-carousel-design-store.ts's loadFamilyImage/saveFamilyImage).
 *
 * This is a deterministic text transform, not a call to any model: it
 * turns that episode's own family-scenario copy into a ready-to-paste
 * prompt so the photo matches the "IT HAPPENS AT HOME" text instead of
 * being generic. "Warm realistic photography" is the one house style used
 * across the whole series, per explicit founder direction, so photos feel
 * consistent episode to episode rather than each looking like a different
 * generator/style.
 *
 * The renderer (drawSlide2BackgroundPhoto in aathichoodi-carousel-
 * renderer.ts) draws this photo full-bleed behind the WHOLE slide, with a
 * tint over roughly the left half (where the text sits) fading to fully
 * clear on the right -- so the composition asked for here matters, not
 * just the subject matter: a photo with its subjects spread across the
 * full width, or weighted left, puts someone under the heaviest part of
 * the tint (confirmed live: a founder-uploaded two-child photo left one
 * child almost unreadable at the left edge). Subjects need to sit inside
 * roughly the right two-thirds of the frame, with the left third kept as
 * calmer, simpler background -- that's what the composition line below
 * is asking for, and it's the one thing worth double-checking before
 * generating: is EVERYONE who matters in the scene inside that right
 * two-thirds already?
 *
 * AUDIENCE, applied to every prompt (not per-episode): the series' actual
 * readership is Tamil families living abroad, not in Tamil Nadu itself --
 * per explicit founder direction, so the ethnicity/appearance line below
 * is fixed the same way the "warm realistic photography" style is, not
 * something to vary per scenario.
 *
 * BACKGROUND/SETTING rotates per episode (BACKGROUND_SETTINGS below,
 * picked via pickFresh keyed on episodeNumber -- same selection.ts helper
 * every other pool in this series uses, just without history tracking
 * since this is generated on demand rather than composed once). Founder-
 * flagged: every copied prompt was landing on the same generic "home"
 * setting (no location specified beyond "real everyday home setting"),
 * so every generated photo looked alike. Rotating the setting doesn't
 * override a scenario that already names a location (see the wording
 * below) -- it only fills in when the scene itself is location-agnostic.
 */

import { pickFresh, type Pickable } from "./selection";

interface BackgroundSetting extends Pickable {
  text: string;
}

const BACKGROUND_SETTINGS: readonly BackgroundSetting[] = [
  { id: "kitchen", text: "at the kitchen counter, soft morning light through a window" },
  { id: "dining-table", text: "at the dining table, a meal still out, warm evening light" },
  { id: "living-room-couch", text: "on the living room couch, a lamp lit in the evening" },
  { id: "study-corner", text: "at a home study corner or desk, books and a desk lamp nearby" },
  { id: "porch-balcony", text: "on a back porch or balcony, potted plants in the background" },
  { id: "front-yard", text: "in the front yard or driveway, natural daylight" },
  { id: "bedroom-nook", text: "in a bedroom reading nook by the window, afternoon light" },
  { id: "entryway", text: "by the front hallway/entryway, shoes and bags set down nearby" },
  { id: "car-back-seat", text: "in the back seat of a car during a drive, seen from behind" },
  { id: "grandparents-home", text: "in a grandparent's living room, an older family member present" },
];

/** Best-effort rewrite of the second-person scenario copy ("Your child
 *  sees...") into a third-person scene description an image generator can
 *  act on ("A child sees..."). Plain word-boundary substitutions, not a
 *  grammar engine -- review the result before pasting it into a generator. */
function toSceneDescription(text: string): string {
  return text
    .replace(/\bYour older child\b/g, "An older child")
    .replace(/\bYour younger child\b/g, "A younger child")
    .replace(/\bYour child\b/g, "A child")
    .replace(/\byour child\b/g, "a child")
    .replace(/\byour children\b/gi, "the children")
    .replace(/\byour family\b/gi, "the family")
    .replace(/\byour\b/gi, "their")
    .replace(/\byou\b/gi, "they");
}

/** familyAngleText should be whatever's CURRENTLY shown on Slide 3 (the
 *  generated scenario, or the founder's own text override if one is set)
 *  so the prompt always matches what the slide actually says. episodeNumber
 *  seeds the rotating background setting (see BACKGROUND_SETTINGS above)
 *  so consecutive episodes don't land on the same generic "home" look. */
export function buildFamilyImagePrompt(familyAngleText: string, episodeNumber: number): string {
  const scene = toSceneDescription(familyAngleText.trim());
  const setting = pickFresh(BACKGROUND_SETTINGS, [], episodeNumber).text;
  return [
    `Warm, realistic documentary-style family photograph. Scene: ${scene}`,
    "The family is Tamil / South Indian in heritage and appearance, living abroad in a Western diaspora country (for example a modern home in the US, UK, Canada, Australia, or Singapore) -- an authentic contemporary diaspora household, not a rural or 'exoticized' village-India setting. Natural, lived-in cultural touches are welcome where they'd realistically appear in such a home (a small home altar or Tamil calendar in the background, a South Indian coffee tumbler, a saree or traditional jewelry worn naturally by an older family member) but should feel everyday, never costumed or staged for the camera.",
    `Natural window light, candid and unposed, soft warm tones, genuine expressions. If the scene above doesn't already specify a location, set it ${setting}.`,
    "Vertical portrait composition (roughly 4:5 aspect ratio). IMPORTANT: keep everyone in the scene within the RIGHT two-thirds of the frame -- the left third should be simple, uncluttered background (a wall, soft shadow, blurred negative space), since that side of the final image will carry overlaid text. Do not spread people or the main action across the full width or toward the left edge.",
    "Photorealistic only -- no text, no logos, no watermarks, no illustration or cartoon style.",
  ].join(" ");
}
